version: "3.9"

services:
  authentication_service:
    restart: always
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/auth_service
    ports:
      - "8080:8080"
    env_file:
      - ./.env
