# Generated by Django 4.1 on 2022-08-08 14:59

import account_service.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account_service", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(
            name="accountuser",
            managers=[("objects", account_service.managers.UserManager())],
        )
    ]
