# Generated by Django 4.1 on 2022-08-08 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("account_service", "0002_alter_accountuser_managers")]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        )
    ]
