name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: some-incredible-djang-secret-key-)
  EMAIL_HOST_PASSWORD: somehost@email.com
  GOOGLE_OAUTH2_CLIENT_ID: some-google-oauth-client-id

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run makemigrations
      run: python manage.py makemigrations
    - name: Run migrations
      run: python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test